name: MongoDB Atlas Connection

on:
  push:
    branches:
      - main

jobs:
  connect-mongodb-atlas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MongoDB Atlas connection
        run: |
          # Récupérez la chaîne de connexion MongoDB Atlas depuis les secrets
          MONGODB_ATLAS_URI=$MONGODB_ATLAS_URI

          # Votre logique de connexion à MongoDB Atlas ici
          # Par exemple, vous pouvez utiliser l'interface de ligne de commande MongoDB (mongosh) ou un script Node.js.

          # Exemple avec mongosh
          mongosh "$MONGODB_ATLAS_URI" --eval "printjson(db.adminCommand('listDatabases'))"
        env:
          MONGODB_ATLAS_URI: ${{ secrets.MONGODB_ATLAS_URI }}
