name: MongoDB Atlas Connection

on:
  push:
    branches:
      - main

jobs:
  connect-mongodb-atlas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install MongoDB Shell
        run: |
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 656408E390CFB1F5
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
          sudo apt-get update
          sudo apt-get install -y mongodb-org-shell
          
      - name: Set up MongoDB Atlas connection
        run: |
          # Récupérez la chaîne de connexion MongoDB Atlas depuis les secrets
          MONGODB_ATLAS_URI=$MONGODB_ATLAS_URI
      
          # Votre logique de connexion à MongoDB Atlas ici
          # Utilisez l'interface de ligne de commande MongoDB "mongo"
          
          # Exemple avec mongo
          mongo "$MONGODB_ATLAS_URI" --eval "printjson(db.adminCommand('listDatabases'))"
        env:
          MONGODB_ATLAS_URI: ${{ secrets.MONGODB_ATLAS_URI }}
