name: Mon Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier l'adresse IP
        run: echo "IP Address: $(curl -s https://api64.ipify.org)"
